# Generated by Django 4.2 on 2024-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PendingSubsidiaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(upload_to='logos')),
                ('address', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('year_established', models.IntegerField()),
                ('business_description', models.TextField()),
                ('social_media_links', models.TextField()),
                ('parent_company_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('operational_status', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_entity_type', models.CharField(max_length=40)),
                ('licensing_authority', models.CharField(max_length=40)),
                ('market', models.CharField(blank=True, max_length=40, null=True)),
                ('subsidiary_code', models.CharField(max_length=30)),
                ('board_members', models.TextField(blank=True, null=True)),
                ('operating_countries', models.TextField(blank=True, null=True)),
                ('compliance_certifications', models.FileField(blank=True, null=True, upload_to='certifications')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Subsidiaries',
            },
        ),
    ]
